# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


##############################################
# Fastlane confiugration file
# Author : Chea Socheat
##############################################

default_platform(:android)

platform :android do
  ############################################
  ## BEFORE ALL 
  ############################################
  before_all do
      # to setup the proper urls, scroll down to part 3
      ENV["SLACK_URL"] ||= "https://hooks.slack.com/services/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" 
      
      slack(message:"Starting deploy newer version...")
  end

  ############################################
  ## BEFORE ALL 
  ############################################
  after_all do |lane|
        # This block is called, only if the executed lane was successful
 
        slack(
           message: "New App Update successfully deployed."
        )
    end


  ############################################
  ## INCASE LANE ERROR
  ############################################
  error do |lane, exception|
        slack(
            message: exception.message,
            success: false
        )
    end


  #######################################
  # LANE : Clean Directory
  #######################################
  desc "Clean directory"
  lane :clean do 
     gradle(task:"clean")
  end 

  #######################################
  # LANE : Run all unit test
  #######################################
  desc "Runs all the tests"
  lane :tests do
    gradle(task: "test")
  end

  #######################################
  # LANE : Capture Screenshots
  #######################################
  desc "Capture Screenshots"
  lane :screenshots do
    capture_android_screenshots
  end

  #######################################
  # LANE : Build Development Debug APK
  #######################################
  desc "Build Development Debug APK"
  lane :build_beta_debug do
     gradle(
      task: 'clean assemble',
      flavor: 'development',
      build_type: 'Debug'
    )
  end


  #######################################
  # LANE : Build Development Release APK
  #######################################
    desc "Build Development Release APK"
    lane :build_beta_release do
      gradle(
        task: 'clean assemble',
        flavor: 'development',
        build_type: 'Release'
      )
    end



  ##########################################
  # LANE : Deploy Beta Version to Play Store
  ##########################################
    desc "Deploy Beta Version to Play Store"
    lane :deploy_beta do
      #tell gradle to clean and build production env
      gradle(
        task: 'clean assemble',
        flavor: 'production',
        build_type: 'Release',
        properties: {
            "versionCode" => 1,
            "versionName" => "1.0.0",
            "android.injected.signing.store.file" => "/Users/cheasocheat/AndroidStudioProjects/PhumMusic/phum_music_release.jks",
            "android.injected.signing.store.password" => "Asva@2019" ,
            "android.injected.signing.key.alias" => "AsvaAlias",
            "android.injected.signing.key.password" => "Asva@2019",
            }
      )

      #upload to store in beta track
      upload_to_play_store(
        track: 'beta'
      )
      #slack(message: 'Successfully distributed a new beta build')
    end

  ##########################################
  # LANE : Submit Beta Build to Crashlytics
  ##########################################
  #desc "Submit a new Beta Build to Crashlytics Beta"
  #lane :beta do
  #  gradle(task: "clean assembleRelease")
  #  crashlytics
 # 
 #   # sh "your_script.sh"
 #   # You can also use other beta testing services here
 # end


  ##########################################
  # LANE : Deploy a new version to the Google Play
  ##########################################
  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end

end